import type { CSSProperties } from "react";

export const speechBubbleStyles: Record<string, CSSProperties> = {
  wrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    backgroundColor: "#ffffff",
    border: "1px solid #dbe2ea",
    borderRadius: "8px",
    padding: "1rem",
    maxHeight: "calc(100vh - 6rem)",
    overflowY: "auto",
    position: "sticky",
    top: "5rem",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.06)",
  },
  title: {
    margin: 0,
    color: "#0f172a",
    fontSize: "1.1rem",
    fontWeight: 800,
  },
  subtitle: {
    margin: "0.15rem 0 0",
    color: "#64748b",
    fontSize: "0.86rem",
  },
  tileGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "0.6rem",
    borderTop: "1px solid #e5eaf0",
    paddingTop: "0.95rem",
  },
  tile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: "0.45rem",
    minWidth: 0,
    minHeight: "7.4rem",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    cursor: "pointer",
    padding: "0.5rem",
  },
  thumbnailFrame: {
    display: "grid",
    placeItems: "center",
    width: "100%",
    aspectRatio: "4 / 3",
    borderRadius: "8px",
    backgroundColor: "#f8fafc",
    border: "1px solid #e5eaf0",
    overflow: "hidden",
  },
  thumbnail: {
    display: "block",
    maxWidth: "92%",
    maxHeight: "92%",
    objectFit: "contain",
    pointerEvents: "none",
    userSelect: "none",
  },
  emptyIcon: {
    color: "#94a3b8",
    fontSize: "1.35rem",
  },
  tileLabel: {
    color: "#334155",
    fontSize: "0.78rem",
    fontWeight: 800,
    lineHeight: 1.25,
    overflowWrap: "anywhere",
    textAlign: "center",
  },
  loadingBlock: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    minHeight: "8rem",
    color: "#64748b",
    fontWeight: 700,
  },
};
