import type { CSSProperties } from "react";

export const selectorStyles: Record<string, CSSProperties> = {
  wrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "0.9rem",
    backgroundColor: "#ffffff",
    border: "1px solid #dbe2ea",
    borderRadius: "8px",
    padding: "1rem",
    maxHeight: "calc(100vh - 6rem)",
    overflowY: "auto",
    position: "sticky",
    top: "5rem",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.06)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
  },
  title: {
    margin: 0,
    color: "#0f172a",
    fontSize: "1.1rem",
    fontWeight: 800,
  },
  subtitle: {
    margin: "0.15rem 0 0",
    color: "#64748b",
    fontSize: "0.86rem",
  },
  tabs: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "0.5rem",
  },
  tab: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.45rem",
    minHeight: "2.35rem",
    border: "1px solid #dbe2ea",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 800,
    padding: "0 0.65rem",
  },
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    borderTop: "1px solid #e5eaf0",
    paddingTop: "0.9rem",
  },
  panelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
  },
  panelTitle: {
    margin: 0,
    color: "#111827",
    fontSize: "1rem",
    fontWeight: 800,
  },
  panelMeta: {
    color: "#64748b",
    fontSize: "0.8rem",
    fontWeight: 700,
  },
  partBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "0.55rem",
  },
  partHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
  },
  partLabel: {
    color: "#1f2937",
    fontSize: "0.9rem",
    fontWeight: 800,
  },
  partCount: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "1.55rem",
    height: "1.35rem",
    borderRadius: "999px",
    backgroundColor: "#edf2f7",
    color: "#475569",
    fontSize: "0.75rem",
    fontWeight: 800,
  },
  tileGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "0.55rem",
  },
  tile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: "0.45rem",
    minWidth: 0,
    minHeight: "7.2rem",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    cursor: "pointer",
    padding: "0.5rem",
  },
  thumbnailFrame: {
    display: "grid",
    placeItems: "center",
    width: "100%",
    aspectRatio: "1 / 1",
    borderRadius: "8px",
    backgroundColor: "#f8fafc",
    border: "1px solid #e5eaf0",
    overflow: "hidden",
  },
  thumbnailStage: {
    position: "relative",
    display: "block",
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  thumbnailLayer: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "100%",
    objectFit: "contain",
    pointerEvents: "none",
    userSelect: "none",
  },
  emptyIcon: {
    display: "grid",
    placeItems: "center",
    width: "100%",
    height: "100%",
    color: "#94a3b8",
    fontSize: "1.25rem",
  },
  tileLabel: {
    display: "block",
    minHeight: "2rem",
    color: "#334155",
    fontSize: "0.78rem",
    fontWeight: 800,
    lineHeight: 1.25,
    overflowWrap: "anywhere",
    textAlign: "center",
  },
  subLabel: {
    color: "#1f2937",
    fontSize: "0.9rem",
    fontWeight: 800,
  },
  colorPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.65rem",
    border: "1px solid #e5eaf0",
    borderRadius: "8px",
    backgroundColor: "#f8fafc",
    padding: "0.75rem",
  },
  colorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
  },
  swatches: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "0.55rem",
  },
  swatch: {
    width: "1.6rem",
    height: "1.6rem",
    border: "2px solid #d1d5db",
    borderRadius: "999px",
    cursor: "pointer",
    padding: 0,
  },
  genderPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.65rem",
    border: "1px solid #e5eaf0",
    borderRadius: "8px",
    backgroundColor: "#f8fafc",
    padding: "0.75rem",
  },
  segmentedControl: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "0.25rem",
    border: "1px solid #dbe2ea",
    borderRadius: "8px",
    backgroundColor: "#ffffff",
    padding: "0.25rem",
  },
  segmentedButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.35rem",
    minHeight: "2.15rem",
    minWidth: 0,
    border: 0,
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "0.78rem",
    fontWeight: 800,
    padding: "0 0.35rem",
    whiteSpace: "normal",
    lineHeight: 1.15,
  },
  colorInput: {
    width: "2rem",
    height: "2rem",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    cursor: "pointer",
    padding: "0.1rem",
    backgroundColor: "#ffffff",
  },
  loadingBlock: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    minHeight: "8rem",
    color: "#64748b",
    fontWeight: 700,
  },
};
