import type { CSSProperties } from "react";

export const headerStyles: Record<string, CSSProperties> = {
  wrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "1rem",
    padding: "0.9rem 1.5rem",
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "#ffffff",
    boxShadow: "0 1px 2px rgba(15, 23, 42, 0.04)",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  titleBlock: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    minWidth: 0,
  },
  logo: {
    display: "block",
    width: "clamp(9.5rem, 16vw, 13.5rem)",
    height: "auto",
    flex: "0 0 auto",
  },
  copyBlock: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  },
  brandMark: {
    display: "grid",
    placeItems: "center",
    width: "2.4rem",
    height: "2.4rem",
    borderRadius: "8px",
    backgroundColor: "#0f766e",
    color: "#ffffff",
    fontWeight: 800,
    flex: "0 0 auto",
  },
  title: {
    margin: 0,
    fontSize: "1.35rem",
    fontWeight: 700,
    lineHeight: 1.1,
  },
  subtitle: {
    margin: 0,
    fontSize: "0.88rem",
    color: "#6b7280",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    flex: "0 0 auto",
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.45rem",
    minHeight: "2.35rem",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    backgroundColor: "#ffffff",
    color: "#111827",
    cursor: "pointer",
    fontWeight: 700,
    padding: "0 0.85rem",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.45rem",
    minHeight: "2.35rem",
    border: "1px solid #0f766e",
    borderRadius: "8px",
    backgroundColor: "#0f766e",
    color: "#ffffff",
    cursor: "pointer",
    fontWeight: 700,
    padding: "0 0.9rem",
  },
  fileInput: {
    display: "none",
  },
};
