import type { CSSProperties } from "react";

export const previewStyles: Record<string, CSSProperties> = {
  wrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.9rem",
    backgroundColor: "#ffffff",
    border: "1px solid #dbe2ea",
    borderRadius: "8px",
    padding: "1.1rem",
    boxShadow: "0 16px 40px rgba(15, 23, 42, 0.07)",
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "1rem",
    width: "100%",
  },
  title: {
    margin: 0,
    color: "#0f172a",
    fontSize: "1.15rem",
    fontWeight: 800,
  },
  subtitle: {
    margin: "0.15rem 0 0",
    color: "#64748b",
    fontSize: "0.86rem",
  },
  canvasMeta: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "1.8rem",
    borderRadius: "999px",
    backgroundColor: "#ecfdf5",
    color: "#0f766e",
    fontSize: "0.8rem",
    fontWeight: 800,
    padding: "0 0.75rem",
  },
  canvas: {
    position: "relative",
    width: 480,
    height: 480,
    border: "1px solid #cbd5e1",
    borderRadius: "8px",
    overflow: "hidden",
    backgroundColor: "#ffffff",
    boxShadow: "inset 0 0 0 1px rgba(15, 23, 42, 0.02)",
  },
  faceGroup: {
    position: "absolute",
  },
  speechBubbleFrame: {
    position: "absolute",
    boxSizing: "border-box",
    cursor: "grab",
    touchAction: "none",
    userSelect: "none",
    zIndex: 5,
  },
  speechBubbleImage: {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "contain",
    pointerEvents: "none",
    userSelect: "none",
  },
  speechBubbleResizeHandle: {
    position: "absolute",
    right: "-0.35rem",
    bottom: "-0.35rem",
    width: "0.9rem",
    height: "0.9rem",
    border: "2px solid #ffffff",
    borderRadius: "999px",
    backgroundColor: "#0f766e",
    boxShadow: "0 0 0 1px rgba(15, 23, 42, 0.16)",
    cursor: "nwse-resize",
    touchAction: "none",
  },
  fullCanvasLayer: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "100%",
    objectFit: "contain",
    pointerEvents: "none",
    userSelect: "none",
  },
};
